{
 "title": "Radio Link Inventory",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Select Region",
    "query": "SELECT DISTINCT region\nFROM grafana_dashboards.radio_link_inventory;"
   },
   {
    "name": "mnemonic",
    "label": "Mnemonic",
    "query": "SELECT DISTINCT mnemonic\nFROM grafana_dashboards.radio_link_inventory\nWHERE mnemonic != 'SFP' AND mnemonic IS NOT NULL AND mnemonic != 'N/A';"
   },
   {
    "name": "linkDistance",
    "label": "Link Distance",
    "query": "0 - 1 : 0 AND 1, 2 - 5 : 2 AND 5, 6 - 10 : 6 AND 10, 11 - 20 : 11 AND 20, 21 - 30 : 21 AND 30, 31 - 40 : 31 AND 40, 41 - 50 : 41 AND 50, 51 - 100 : 51 AND 100, 101 - 500 : 101 AND 500,  All : 0 AND 500"
   },
   {
    "name": "inLag",
    "label": "In LAG",
    "query": "SELECT DISTINCT inLag\nFROM grafana_dashboards.radio_link_inventory;"
   },
   {
    "name": "maxCapacity",
    "label": "Max Capacity(Mbps)",
    "query": "0 - 100 : 0 AND 100, 101 - 200 : 101 AND 200, 201 - 300 : 201 AND 300, 301 - 400 : 301 AND 400, 401 - 500 : 401 AND 500, 501 - 1000 : 501 AND 1000, 1001 - 2000 : 1001 AND 2000, 2001 - 3000 : 3001 AND 4000, 4001 - 5000, All : 0 AND 5000"
   }
  ]
 },
 "panels": [
  {
   "title": "Frequency Band Vs Radio Link Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "cards_inventory",
     "rawSql": "SELECT Band, \r\n       SUM(`Tx Frequency (GHz)`) AS `Total Tx Frequency Count`, \r\n       SUM(`Rx Frequency Count`) AS `Total Rx Frequency Count`\r\nFROM (\r\n    SELECT CAST(TxBand AS UNSIGNED) AS Band, \r\n           COUNT(TxBand) AS `Tx Frequency (GHz)`, \r\n           NULL AS `Rx Frequency Count`\r\n    FROM grafana_dashboards.radio_link_inventory\r\n    WHERE TxBand != 'N/A' \r\n          AND region IN ($region) \r\n          AND mnemonic IN ($mnemonic) \r\n    GROUP BY TxBand\r\n\r\n    UNION ALL\r\n\r\n    SELECT CAST(RxBand AS UNSIGNED) AS Band, \r\n           NULL AS `Tx Frequency (GHz)`, \r\n           COUNT(`RxFrequency(Ghz)`) AS `Rx Frequency Count`\r\n    FROM grafana_dashboards.radio_link_inventory\r\n    WHERE RxBand != 'N/A' \r\n          AND region IN ($region) \r\n          AND mnemonic IN ($mnemonic)\r\n    GROUP BY RxBand\r\n) AS subquery\r\nGROUP BY Band\r\nORDER BY CAST(Band AS UNSIGNED);\r\n"
    }
   ]
  },
  {
   "title": "Radio Link Per LinkDistance (Km) ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cards_inventory",
     "rawSql": "SELECT\r\n    COUNT(CASE WHEN `linkDistance(km)` BETWEEN 0 and 1  THEN 1 END) AS `0 - 0.99`,\r\n    COUNT(CASE WHEN `linkDistance(km)` BETWEEN 1 and 5  THEN 1 END) AS `1 - 4.99`,\r\n    COUNT(CASE WHEN `linkDistance(km)` BETWEEN 5 and 10  THEN 1 END) AS `5 - 9.99`,\r\n    COUNT(CASE WHEN `linkDistance(km)` BETWEEN 10 and 20  THEN 1 END) AS `10 - 19.99`,\r\n    COUNT(CASE WHEN `linkDistance(km)` BETWEEN 20 and 30  THEN 1 END) AS `20 - 29.99`,\r\n    COUNT(CASE WHEN `linkDistance(km)` BETWEEN 30 and 40  THEN 1 END) AS `30 - 39.99`,\r\n    COUNT(CASE WHEN `linkDistance(km)` BETWEEN 40 and 50  THEN 1 END) AS `40 - 49.99`,\r\n    COUNT(CASE WHEN `linkDistance(km)` BETWEEN 50 and 100  THEN 1 END) AS `50 - 99.99`,\r\n    COUNT(CASE WHEN `linkDistance(km)` BETWEEN 100 and 500  THEN 1 END) AS `100 - 499.99`\r\nFROM \r\n    grafana_dashboards.radio_link_inventory\r\nWHERE\r\n    region in ($region) AND mnemonic IN ($mnemonic) AND RxBand IN ('7','13','18','38','80');"
    }
   ]
  },
  {
   "title": "Radio Link Per MaxCapacity (Mbps)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cards_inventory",
     "rawSql": "SELECT\r\n    COUNT(CASE WHEN `maxCapacity(Mbps)` BETWEEN 0 and 100  THEN 1 END) AS `0 - 99.99`,\r\n    COUNT(CASE WHEN `maxCapacity(Mbps)` BETWEEN 100 and 200  THEN 1 END) AS `100 - 199.99`,\r\n    COUNT(CASE WHEN `maxCapacity(Mbps)` BETWEEN 200 and 300  THEN 1 END) AS `200 - 299.99`,\r\n    COUNT(CASE WHEN `maxCapacity(Mbps)` BETWEEN 300 and 400  THEN 1 END) AS `300 - 399.99`,\r\n    COUNT(CASE WHEN `maxCapacity(Mbps)` BETWEEN 400 and 500  THEN 1 END) AS `400 - 499.99`,\r\n    COUNT(CASE WHEN `maxCapacity(Mbps)` BETWEEN 500 and 1000  THEN 1 END) AS `500 - 999.99`,\r\n    COUNT(CASE WHEN `maxCapacity(Mbps)` BETWEEN 1000 and 2000  THEN 1 END) AS `1000 - 1999.99`,\r\n    COUNT(CASE WHEN `maxCapacity(Mbps)` BETWEEN 2000 and 3000  THEN 1 END) AS `2000 - 2999.99`,\r\n    COUNT(CASE WHEN `maxCapacity(Mbps)` BETWEEN 3000 and 4000  THEN 1 END) AS `3000 - 3999.99`,\r\n    COUNT(CASE WHEN `maxCapacity(Mbps)` BETWEEN 4000 and 10000  THEN 1 END) AS `4000 - 9999.99`\r\nFROM \r\n    grafana_dashboards.radio_link_inventory\r\nWHERE\r\n    region in ($region) AND mnemonic IN ($mnemonic) AND RxBand IN ('7','13','18','38','80');"
    }
   ]
  }
 ]
}